### ISSUE TITLE
Stations sounding and operating on HFN/HFL are being logged and triangulated

### ISSUE THREAD

**Issue by pinztrek** [s2underground/GhostNet#23]
All, I would recommend removing the HFN/HFL ALE entries as all traffic on those networks are being logged with enough information to triangulate. 

Not going to lecture about illegal operating, but word to the wise, you are attracting attention of the wrong kind to the wrong folks. Many Fed or Fed adjacent on those freqs. Are is this a Fed glow entrapment scheme??? :-)

I'd recommend using your ham callsigns for HFN/HFL, and get on the air legally. Great practice. I2G will support different callsigns for different ALE networks, it's nice in that regard if you don't mind the stealth logging. 

Interesting project though

**Comment by s2underground** [comment]
Look, I don't know what your problem is, but this is a perfectly legal project within the field of amateur radio. AT NO POINT IS ILLEGAL OPERATION ENCOURAGED. Of course every single nationstate actor has been able to triangulate HF radio transmissions to some degree and with varying levels of accuracy. I have provided hours of content on this matter, including mitigation techniques. But coming onto my project and accusing myself and others of impropriety is getting on my last nerve. 

Risk assessment is on the individual user, but I try to make the risks well known while not overinflating minor risks into apocalyptic level problems. If people don't want to use HFN, then don't. The freqs I chose so far aren't on the HFN network anyway, unless they've changed them recently. 

I welcome constructive feedback, but this ain't it. Besides, swooping in and pointing the finger and constantly crying "Fed!" is exactly what feds love to do anyway, simply to tear down and discredit a project that is helping people.

If you don't like the project, then don't engage with it. So far, I'm the only dang person in the entirety of ham radio that has gone this far to help people, especially when it comes to risk management.

**Comment by pinztrek** [comment]
No problem on my end... as I said it's an interesting project. And to give credit where credit is due, nicely documented.

And to be very clear: I'm not discrediting or tearing down anything. Nothing in my comment/issue provided that. It's a issue/defect/bug that your codeplug allows/enables operation on HFN/HFL with bogus callsigns. It should at least be disabled, with a clear "Insert_your_callsign" disclaimer. 

Just fair warning: illegal operation on HFN/HFL is occurring nightly and is enabled by this. If you were serious about being ham responsible you'd have a warning not to operate on HFN/HFL without a valid callsign as it is 100% logged/monitored.

Some of the recent traffic logged is of Fed interest and has attracted attention the users probably do not want. 

If you chose not to believe Fed/Fed adjacent, then that's your risk. You simply are ignorant of who's involved and what they are involved in. Likewise the use of closed source SW. 

Personally, I don't care what you do on ghostnet ham freqs. But just be aware: on HFN/HFL, *all* traffic is logged/monitored, by all participating stations. And other mechanisms. 

Other than the illegal ops usage, I support the concept of the project.

**Comment by s2underground** [comment]
You literally opened an issue on my project making accusations, and directly calling this an entrapment scheme. Why on earth would I listen to you after insulting me like that? Nevertheless, what you are describing is probably something for the developers of Ion2G. I just use their software, I don't have any hand in how any of it works.

Per the FCC, it's up to the user to make sure their license is appropriate for the bands they want to transmit on, and to ensure proper radio etiquette is maintained, and so on. We all know this. I do find it quite interesting that almost 99% of all of the illegal stuff I've seen on HF radio over the years has come from licensed amateurs themselves. Accusing others of what they themselves are guilty of. I personally discourage the unlicensed use of radio, or the violation of any and all FCC regulations. As the airwaves cannot be contained, however, there's not much I can do about it. Nor can anyone else, that's the FCC's job.

**Comment by tim292stro** [comment]
I have also seen that due to "self policing" of the amateur radio sphere, HAMs tend to act like Karens on an HOA
